version: '3.8'

services:
  qa-worksheet-generator:
    build: 
      context: .
      dockerfile: Dockerfile.bulletproof
    container_name: qa_worksheet_generator
    ports:
      - "8081:8081"
    environment:
      - HOST=0.0.0.0
      - PORT=8081
      - MONGO_URI=${MONGO_URI:-mongodb://ai:VgjVpcllJjhYy2c@65.109.31.94:27017/ien?authSource=ien}
      - DB_NAME=${DB_NAME:-ien}
    volumes:
      # Mount logs for persistence
      - ./logs:/app/logs
      # Mount entire project directory (alternative approach)
      # - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - qa-worksheet-network

networks:
  qa-worksheet-network:
    driver: bridge
