version: '3.8'

services:
  qa-worksheet-generator:
    build: 
      context: .
      dockerfile: Dockerfile.bulletproof
      # Alternative dockerfiles if build fails:
      # dockerfile: Dockerfile.minimal
      # dockerfile: Dockerfile
    container_name: qa_worksheet_generator
    ports:
      - "8081:8081"
    environment:
      - HOST=0.0.0.0
      - PORT=8081
      - MONGO_URI=${MONGO_URI:-mongodb://ai:VgjVpcllJjhYy2c@65.109.31.94:27017/ien?authSource=ien}
      - DB_NAME=${DB_NAME:-ien}
    volumes:
      # Mount logs for persistence
      - ./logs:/app/logs
      # Mount logo if you have a local one
      - ./logo.png:/app/logo.png
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - qa-worksheet-network

  # Optional: MongoDB container for local development
  # Uncomment if you want to run MongoDB locally instead of using the remote one
  # mongodb:
  #   image: mongo:7.0
  #   container_name: qa_mongodb
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=password
  #     - MONGO_INITDB_DATABASE=ien
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - qa-worksheet-network

networks:
  qa-worksheet-network:
    driver: bridge

# volumes:
#   mongodb_data:
