services:
  qa-worksheet-generator:
    image: python:3.11-slim
    container_name: qa_worksheet_generator
    working_dir: /app
    command: >
      bash -c "
      apt-get update && 
      apt-get install -y --no-install-recommends curl wget && 
      pip install --upgrade pip --root-user-action=ignore && 
      if [ -f requirements.txt ]; then 
        pip install -r requirements.txt --root-user-action=ignore; 
      else 
        echo 'requirements.txt not found, installing basic packages...'; 
        pip install fastapi uvicorn pymongo boto3 motor python-multipart --root-user-action=ignore; 
      fi &&
      pip install weasyprint reportlab pypdf2 --root-user-action=ignore && 
      ls -la /app &&
      echo 'Starting application...' &&
      python -m uvicorn app:app --host 0.0.0.0 --port 8081
      "
    ports:
      - "8081:8081"
    environment:
      # Docker environment
      - DEBIAN_FRONTEND=noninteractive
      # Application settings
      - HOST=0.0.0.0
      - PORT=8081
      - DEBUG=${DEBUG:-false}
      
      # Database configuration
      - MONGO_URI=${MONGO_URI:-mongodb://ai:VgjVpcllJjhYy2c@65.109.31.94:27017/ien?authSource=ien}
      - DB_NAME=${DB_NAME:-ien}
      
      # S3/Cloudflare R2 configuration
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ACCOUNT_ID=${S3_ACCOUNT_ID}
      - S3_API_TOKEN=${S3_API_TOKEN}
      
      # PDF conversion settings (using Python libraries)
      - PDF_CONVERSION_TIMEOUT=60
      - PDF_CONVERSION_RETRIES=3
      - PDF_CONVERSION_METHOD=weasyprint
      - PDF_CONVERSION_AVAILABLE=true
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
    volumes:
      # Mount the entire project directory
      - .:/app
      # Mount logs for persistence
      - ./logs:/app/logs
      # Mount temp directory for file processing
      - ./temp:/app/temp
      
    restart: "no"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/docs"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 90s
      
    # Resource limits optimized for PDF conversion
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
          
    networks:
      - qa-worksheet-network

networks:
  qa-worksheet-network:
    driver: bridge
